FROM python:3.11

WORKDIR /code

COPY requirements.txt /code/requirements.txt

RUN pip install -r requirements.txt

COPY main.py /code/main.py
COPY ./src /code/src

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]