version: '0.1.0'

services:
  maggus:
    image: bavarianbot:latest
    env_file: .env
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./volumes/db:/code/db:Z
      - ./volumes/data:/code/data:Z

networks:
  default:
    name: maggnet