version: '0.1.0'

services:
  maggus:
    image: bavarianbot:latest
    env_file: .dev.env
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./volumes/db:/code/db

networks:
  default:
    name: maggnet