# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run tests

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**.py'
      - '.github/workflows/**.yaml'
      - '.github/workflows/**.yml'
      - 'tests/**.py'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**.py'
      - '.github/workflows/**.yaml'
      - '.github/workflows/**.yml'
      - 'tests/**.py'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    - name: Test Maggus
      run: |
        pytest --cov-report term-missing --cov-fail-under=66 --cov=src/ tests/